post http://127.0.0.1:8080/Finance/api/User/Authenticate
Content-Type: application/json

{
    "mobile": "2",
    "password": "c4ca4238a0b923820dcc509a6f75849b"
}


###
post http://127.0.0.1:8080/Finance/api/User/SMS
Content-Type: application/json

{
    "mobile": "09305105691"
}

####
POST http://127.0.0.1:8080/Finance/api/Anbar
Content-Type: application/json

{
    "filter": "0", 
    "token": "2C034071-F9F2-4AFD-864A-35D6DAB11B2E"
}


###
POST http://127.0.0.1:8080/PamaApi/api/F2Key/Bank
Content-Type: application/json

{
    "token": "289D8725-561A-4A09-AC29-C5FFAEFE2AD7"
}


####
POST https://RestfulSms.com/api/Token
Content-Type: application/json

{
	"UserApiKey":"b60b459c21eb9446a001459c",
	"SecretKey":"P@ssw0rds**!@"
}

####
POST https://RestfulSms.com/api/MessageSend
Content-Type : application/json
x-sms-ir-secure-token : sss

{
  "Messages":["اومد بکال ساعت دقیق یادت باشه"],
  "MobileNumbers": ["09120282990"],
  "LineNumber": "30002577625785",
  "SendDateTime": "",
  "CanContinueInCaseOfError": "false",
}